version: '3.8'

services:
    postgres:
        container_name: mirea_backend_course_work_db
        image: postgres
        restart: on-failure
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: AnyLogicDB
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - '8080:5432'
volumes:
    database: